[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://siroj-hoyolab-clone.netlify.app"
    Access-Control-Allow-Credentials = "true"